# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: guhernan <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/14 15:53:30 by guhernan          #+#    #+#              #
#    Updated: 2021/12/16 14:01:53 by guhernan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/guhernan/data/db_volume
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/guhernan/data/wordpress_volume
      o: bind

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge


services :

  db:
    container_name: db
    tty: true
    stdin_open: true
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    # env_file: mariadb.env
    environment:
      MYSQL_WORDPRESS_HOST: wordpress:9000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_data
      MYSQL_USER: guhernan
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_volume:/var/lib/mysql:rw
    networks:
      - "nginx_network"
      - "db_network"
    restart: always
  
  
  wordpress:
    depends_on:
      - db
    container_name: wordpress
    tty: true
    stdin_open: true
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_NGINX_HOST: nginx:443
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: guhernan
      WORDPRESS_DB_NAME: wordpress_data
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress:rw
    # env_file: wordpress.env
    networks:
      - "nginx_network"
      - "db_network"
    restart: always
 

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    tty: true
    stdin_open: true
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    # env_file: nginx.env
    environment:
      NGINX_WORDPRESS_HOST: wordpress:9000
    volumes:
       - wordpress_volume:/var/www/html:rw
    ports:
      - "443:443"
    networks:
      - "nginx_network"
    restart: always 
   
